# Generated by Django 5.1.3 on 2025-01-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_interests_userprofile_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(choices=[('personal_development', 'Personal Development'), ('productivity', 'Productivity'), ('stress_management', 'Stress Management'), ('family', 'Family'), ('faith', 'Christian Faith'), ('health', 'Health'), ('studies', 'Studies'), ('self_care', 'Self Care'), ('mindfulness', 'Mindfulness'), ('career_growth', 'Career Growth'), ('others', 'Others')], default='self_care', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
