# Generated by Django 5.1.3 on 2024-12-18 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_habit_daily_tracking_remove_habit_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='daily_tracking',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HabitStatus',
        ),
    ]
