# Generated by Django 5.1.3 on 2024-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_habitcategory_remove_habit_daily_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='target_frequency',
            field=models.PositiveIntegerField(help_text='Target times for the chosen frequency', null=True),
        ),
    ]
