# Generated by Django 5.1.3 on 2024-12-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_autoevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='occurrence_count',
            field=models.IntegerField(default='2'),
        ),
    ]
