# Generated by Django 5.1.3 on 2024-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_habit_occurrence_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='occurrence_count',
            new_name='occurrences',
        ),
        migrations.AddField(
            model_name='habittracking',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='habittracking',
            unique_together={('habit', 'date', 'occurrence_count')},
        ),
    ]
