# Generated by Django 5.1.3 on 2025-01-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_occurrence_count_habit_occurrences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcategory',
            name='name',
            field=models.CharField(choices=[('sport', 'Sport'), ('family', 'Family'), ('self_development', 'Self-development'), ('perfect_morning', 'Perfect Morning'), ('self_care', 'Self-care'), ('food', 'Food')], default='self_care', max_length=100, unique=True),
        ),
    ]
