# Generated by Django 5.1.3 on 2025-01-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_habitcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.habitcategory'),
        ),
    ]
