# Generated by Django 5.1.3 on 2025-01-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingstoachieve',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.folder'),
        ),
    ]
